package co.com.carpco.altablero.hibernate.entities;
// Generated 30-oct-2014 21:20:19 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BzClassRoomXuser generated by hbm2java
 */
public class BzClassRoomXuser  implements java.io.Serializable {


     private BzClassRoomXuserId id;
     private BzClassRoom bzClassRoom;
     private BzUser bzUser;
     private Date creation;
     private Date updated;
     private boolean enabled;

    public BzClassRoomXuser() {
    }

    public BzClassRoomXuser(BzClassRoomXuserId id, BzClassRoom bzClassRoom, BzUser bzUser, Date creation, Date updated, boolean enabled) {
       this.id = id;
       this.bzClassRoom = bzClassRoom;
       this.bzUser = bzUser;
       this.creation = creation;
       this.updated = updated;
       this.enabled = enabled;
    }
   
    public BzClassRoomXuserId getId() {
        return this.id;
    }
    
    public void setId(BzClassRoomXuserId id) {
        this.id = id;
    }
    public BzClassRoom getBzClassRoom() {
        return this.bzClassRoom;
    }
    
    public void setBzClassRoom(BzClassRoom bzClassRoom) {
        this.bzClassRoom = bzClassRoom;
    }
    public BzUser getBzUser() {
        return this.bzUser;
    }
    
    public void setBzUser(BzUser bzUser) {
        this.bzUser = bzUser;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }




}


