package co.com.carpco.altablero.hibernate.entities;
// Generated 07-oct-2014 8:22:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BzClassRoom generated by hbm2java
 */
public class BzClassRoom  implements java.io.Serializable {


     private Integer id;
     private BzGrade bzGrade;
     private BzUser bzUser;
     private String code;
     private String name;
     private Date creation;
     private Date updated;
     private boolean enabled;
     private Set<BzClass> bzClasses = new HashSet<BzClass>(0);

    public BzClassRoom() {
    }

	
    public BzClassRoom(BzGrade bzGrade, BzUser bzUser, String code, String name, Date creation, Date updated, boolean enabled) {
        this.bzGrade = bzGrade;
        this.bzUser = bzUser;
        this.code = code;
        this.name = name;
        this.creation = creation;
        this.updated = updated;
        this.enabled = enabled;
    }
    public BzClassRoom(BzGrade bzGrade, BzUser bzUser, String code, String name, Date creation, Date updated, boolean enabled, Set<BzClass> bzClasses) {
       this.bzGrade = bzGrade;
       this.bzUser = bzUser;
       this.code = code;
       this.name = name;
       this.creation = creation;
       this.updated = updated;
       this.enabled = enabled;
       this.bzClasses = bzClasses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public BzGrade getBzGrade() {
        return this.bzGrade;
    }
    
    public void setBzGrade(BzGrade bzGrade) {
        this.bzGrade = bzGrade;
    }
    public BzUser getBzUser() {
        return this.bzUser;
    }
    
    public void setBzUser(BzUser bzUser) {
        this.bzUser = bzUser;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public Set<BzClass> getBzClasses() {
        return this.bzClasses;
    }
    
    public void setBzClasses(Set<BzClass> bzClasses) {
        this.bzClasses = bzClasses;
    }




}


