package co.com.carpco.altablero.hibernate.entities;
// Generated 11-nov-2014 9:05:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BzClass generated by hbm2java
 */
public class BzClass  implements java.io.Serializable {


     private Integer id;
     private BzClassRoom bzClassRoom;
     private BzSubject bzSubject;
     private BzUser bzUser;
     private String name;
     private Date creation;
     private Date updated;
     private boolean enabled;
     private Set<BzNoteDefinition> bzNoteDefinitions = new HashSet<BzNoteDefinition>(0);

    public BzClass() {
    }

	
    public BzClass(BzClassRoom bzClassRoom, BzSubject bzSubject, BzUser bzUser, String name, Date creation, Date updated, boolean enabled) {
        this.bzClassRoom = bzClassRoom;
        this.bzSubject = bzSubject;
        this.bzUser = bzUser;
        this.name = name;
        this.creation = creation;
        this.updated = updated;
        this.enabled = enabled;
    }
    public BzClass(BzClassRoom bzClassRoom, BzSubject bzSubject, BzUser bzUser, String name, Date creation, Date updated, boolean enabled, Set<BzNoteDefinition> bzNoteDefinitions) {
       this.bzClassRoom = bzClassRoom;
       this.bzSubject = bzSubject;
       this.bzUser = bzUser;
       this.name = name;
       this.creation = creation;
       this.updated = updated;
       this.enabled = enabled;
       this.bzNoteDefinitions = bzNoteDefinitions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public BzClassRoom getBzClassRoom() {
        return this.bzClassRoom;
    }
    
    public void setBzClassRoom(BzClassRoom bzClassRoom) {
        this.bzClassRoom = bzClassRoom;
    }
    public BzSubject getBzSubject() {
        return this.bzSubject;
    }
    
    public void setBzSubject(BzSubject bzSubject) {
        this.bzSubject = bzSubject;
    }
    public BzUser getBzUser() {
        return this.bzUser;
    }
    
    public void setBzUser(BzUser bzUser) {
        this.bzUser = bzUser;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public Set<BzNoteDefinition> getBzNoteDefinitions() {
        return this.bzNoteDefinitions;
    }
    
    public void setBzNoteDefinitions(Set<BzNoteDefinition> bzNoteDefinitions) {
        this.bzNoteDefinitions = bzNoteDefinitions;
    }




}


