package co.com.carpco.altablero.hibernate.entities;
// Generated 11-nov-2014 9:05:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BzClassRoom generated by hbm2java
 */
public class BzClassRoom  implements java.io.Serializable {


     private Integer id;
     private BzGrade bzGrade;
     private BzSchool bzSchool;
     private BzUser bzUser;
     private BzYear bzYear;
     private String code;
     private String name;
     private Date creation;
     private Date updated;
     private boolean enabled;
     private Set<BzClass> bzClasses = new HashSet<BzClass>(0);
     private Set<BzClassRoomXuser> bzClassRoomXusers = new HashSet<BzClassRoomXuser>(0);

    public BzClassRoom() {
    }

	
    public BzClassRoom(BzGrade bzGrade, BzSchool bzSchool, BzUser bzUser, BzYear bzYear, String code, String name, Date creation, Date updated, boolean enabled) {
        this.bzGrade = bzGrade;
        this.bzSchool = bzSchool;
        this.bzUser = bzUser;
        this.bzYear = bzYear;
        this.code = code;
        this.name = name;
        this.creation = creation;
        this.updated = updated;
        this.enabled = enabled;
    }
    public BzClassRoom(BzGrade bzGrade, BzSchool bzSchool, BzUser bzUser, BzYear bzYear, String code, String name, Date creation, Date updated, boolean enabled, Set<BzClass> bzClasses, Set<BzClassRoomXuser> bzClassRoomXusers) {
       this.bzGrade = bzGrade;
       this.bzSchool = bzSchool;
       this.bzUser = bzUser;
       this.bzYear = bzYear;
       this.code = code;
       this.name = name;
       this.creation = creation;
       this.updated = updated;
       this.enabled = enabled;
       this.bzClasses = bzClasses;
       this.bzClassRoomXusers = bzClassRoomXusers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public BzGrade getBzGrade() {
        return this.bzGrade;
    }
    
    public void setBzGrade(BzGrade bzGrade) {
        this.bzGrade = bzGrade;
    }
    public BzSchool getBzSchool() {
        return this.bzSchool;
    }
    
    public void setBzSchool(BzSchool bzSchool) {
        this.bzSchool = bzSchool;
    }
    public BzUser getBzUser() {
        return this.bzUser;
    }
    
    public void setBzUser(BzUser bzUser) {
        this.bzUser = bzUser;
    }
    public BzYear getBzYear() {
        return this.bzYear;
    }
    
    public void setBzYear(BzYear bzYear) {
        this.bzYear = bzYear;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public Set<BzClass> getBzClasses() {
        return this.bzClasses;
    }
    
    public void setBzClasses(Set<BzClass> bzClasses) {
        this.bzClasses = bzClasses;
    }
    public Set<BzClassRoomXuser> getBzClassRoomXusers() {
        return this.bzClassRoomXusers;
    }
    
    public void setBzClassRoomXusers(Set<BzClassRoomXuser> bzClassRoomXusers) {
        this.bzClassRoomXusers = bzClassRoomXusers;
    }




}


