package co.com.carpco.altablero.hibernate.entities;
// Generated 24-sep-2014 23:08:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * BzNoteDefinition generated by hbm2java
 */
public class BzNoteDefinition  implements java.io.Serializable {


     private Integer id;
     private BzClass bzClass;
     private BzPeriod bzPeriod;
     private String name;
     private String description;
     private BigDecimal value;
     private Date creation;
     private Date updated;
     private boolean enabled;

    public BzNoteDefinition() {
    }

    public BzNoteDefinition(BzClass bzClass, BzPeriod bzPeriod, String name, String description, BigDecimal value, Date creation, Date updated, boolean enabled) {
       this.bzClass = bzClass;
       this.bzPeriod = bzPeriod;
       this.name = name;
       this.description = description;
       this.value = value;
       this.creation = creation;
       this.updated = updated;
       this.enabled = enabled;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public BzClass getBzClass() {
        return this.bzClass;
    }
    
    public void setBzClass(BzClass bzClass) {
        this.bzClass = bzClass;
    }
    public BzPeriod getBzPeriod() {
        return this.bzPeriod;
    }
    
    public void setBzPeriod(BzPeriod bzPeriod) {
        this.bzPeriod = bzPeriod;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getValue() {
        return this.value;
    }
    
    public void setValue(BigDecimal value) {
        this.value = value;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }




}


