package co.com.carpco.altablero.hibernate.entities;
// Generated 07-oct-2014 8:22:25 by Hibernate Tools 4.3.1



/**
 * BzNoteValueId generated by hbm2java
 */
public class BzNoteValueId  implements java.io.Serializable {


     private int idNoteDefinition;
     private int idUser;

    public BzNoteValueId() {
    }

    public BzNoteValueId(int idNoteDefinition, int idUser) {
       this.idNoteDefinition = idNoteDefinition;
       this.idUser = idUser;
    }
   
    public int getIdNoteDefinition() {
        return this.idNoteDefinition;
    }
    
    public void setIdNoteDefinition(int idNoteDefinition) {
        this.idNoteDefinition = idNoteDefinition;
    }
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BzNoteValueId) ) return false;
		 BzNoteValueId castOther = ( BzNoteValueId ) other; 
         
		 return (this.getIdNoteDefinition()==castOther.getIdNoteDefinition())
 && (this.getIdUser()==castOther.getIdUser());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdNoteDefinition();
         result = 37 * result + this.getIdUser();
         return result;
   }   


}


