package co.com.carpco.altablero.hibernate.entities;
// Generated 24-sep-2014 23:08:01 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BzPeriod generated by hbm2java
 */
public class BzPeriod  implements java.io.Serializable {


     private Integer id;
     private BzYear bzYear;
     private String name;
     private Date creation;
     private Date updated;
     private boolean enabled;
     private Set<BzNoteDefinition> bzNoteDefinitions = new HashSet<BzNoteDefinition>(0);

    public BzPeriod() {
    }

	
    public BzPeriod(BzYear bzYear, String name, Date creation, Date updated, boolean enabled) {
        this.bzYear = bzYear;
        this.name = name;
        this.creation = creation;
        this.updated = updated;
        this.enabled = enabled;
    }
    public BzPeriod(BzYear bzYear, String name, Date creation, Date updated, boolean enabled, Set<BzNoteDefinition> bzNoteDefinitions) {
       this.bzYear = bzYear;
       this.name = name;
       this.creation = creation;
       this.updated = updated;
       this.enabled = enabled;
       this.bzNoteDefinitions = bzNoteDefinitions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public BzYear getBzYear() {
        return this.bzYear;
    }
    
    public void setBzYear(BzYear bzYear) {
        this.bzYear = bzYear;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public Set<BzNoteDefinition> getBzNoteDefinitions() {
        return this.bzNoteDefinitions;
    }
    
    public void setBzNoteDefinitions(Set<BzNoteDefinition> bzNoteDefinitions) {
        this.bzNoteDefinitions = bzNoteDefinitions;
    }




}


