package co.com.carpco.altablero.hibernate.entities;
// Generated 24-sep-2014 23:08:01 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BzSchool generated by hbm2java
 */
public class BzSchool  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String name;
     private Date creation;
     private Date updated;
     private boolean enabled;
     private Set<BzYear> bzYears = new HashSet<BzYear>(0);

    public BzSchool() {
    }

	
    public BzSchool(String code, String name, Date creation, Date updated, boolean enabled) {
        this.code = code;
        this.name = name;
        this.creation = creation;
        this.updated = updated;
        this.enabled = enabled;
    }
    public BzSchool(String code, String name, Date creation, Date updated, boolean enabled, Set<BzYear> bzYears) {
       this.code = code;
       this.name = name;
       this.creation = creation;
       this.updated = updated;
       this.enabled = enabled;
       this.bzYears = bzYears;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public Set<BzYear> getBzYears() {
        return this.bzYears;
    }
    
    public void setBzYears(Set<BzYear> bzYears) {
        this.bzYears = bzYears;
    }




}


