package co.com.carpco.altablero.hibernate.entities;
// Generated 07-oct-2014 8:22:25 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BzSchoolXuser generated by hbm2java
 */
public class BzSchoolXuser  implements java.io.Serializable {


     private BzSchoolXuserId id;
     private BzSchool bzSchool;
     private BzUser bzUser;
     private Date creation;
     private Date updated;
     private boolean enabled;

    public BzSchoolXuser() {
    }

    public BzSchoolXuser(BzSchoolXuserId id, BzSchool bzSchool, BzUser bzUser, Date creation, Date updated, boolean enabled) {
       this.id = id;
       this.bzSchool = bzSchool;
       this.bzUser = bzUser;
       this.creation = creation;
       this.updated = updated;
       this.enabled = enabled;
    }
   
    public BzSchoolXuserId getId() {
        return this.id;
    }
    
    public void setId(BzSchoolXuserId id) {
        this.id = id;
    }
    public BzSchool getBzSchool() {
        return this.bzSchool;
    }
    
    public void setBzSchool(BzSchool bzSchool) {
        this.bzSchool = bzSchool;
    }
    public BzUser getBzUser() {
        return this.bzUser;
    }
    
    public void setBzUser(BzUser bzUser) {
        this.bzUser = bzUser;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }




}


