package co.com.carpco.altablero.hibernate.entities;
// Generated 11-nov-2014 9:05:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BzSchool generated by hbm2java
 */
public class BzSchool  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String name;
     private Date creation;
     private Date updated;
     private boolean enabled;
     private Set<BzSchoolXuser> bzSchoolXusers = new HashSet<BzSchoolXuser>(0);
     private Set<BzClassRoom> bzClassRooms = new HashSet<BzClassRoom>(0);

    public BzSchool() {
    }

	
    public BzSchool(String code, String name, Date creation, Date updated, boolean enabled) {
        this.code = code;
        this.name = name;
        this.creation = creation;
        this.updated = updated;
        this.enabled = enabled;
    }
    public BzSchool(String code, String name, Date creation, Date updated, boolean enabled, Set<BzSchoolXuser> bzSchoolXusers, Set<BzClassRoom> bzClassRooms) {
       this.code = code;
       this.name = name;
       this.creation = creation;
       this.updated = updated;
       this.enabled = enabled;
       this.bzSchoolXusers = bzSchoolXusers;
       this.bzClassRooms = bzClassRooms;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public Set<BzSchoolXuser> getBzSchoolXusers() {
        return this.bzSchoolXusers;
    }
    
    public void setBzSchoolXusers(Set<BzSchoolXuser> bzSchoolXusers) {
        this.bzSchoolXusers = bzSchoolXusers;
    }
    public Set<BzClassRoom> getBzClassRooms() {
        return this.bzClassRooms;
    }
    
    public void setBzClassRooms(Set<BzClassRoom> bzClassRooms) {
        this.bzClassRooms = bzClassRooms;
    }




}


