package co.com.carpco.altablero.hibernate.entities;
// Generated 07-oct-2014 8:22:25 by Hibernate Tools 4.3.1



/**
 * BzSchoolXuserId generated by hbm2java
 */
public class BzSchoolXuserId  implements java.io.Serializable {


     private int idSchool;
     private int idUser;

    public BzSchoolXuserId() {
    }

    public BzSchoolXuserId(int idSchool, int idUser) {
       this.idSchool = idSchool;
       this.idUser = idUser;
    }
   
    public int getIdSchool() {
        return this.idSchool;
    }
    
    public void setIdSchool(int idSchool) {
        this.idSchool = idSchool;
    }
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BzSchoolXuserId) ) return false;
		 BzSchoolXuserId castOther = ( BzSchoolXuserId ) other; 
         
		 return (this.getIdSchool()==castOther.getIdSchool())
 && (this.getIdUser()==castOther.getIdUser());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdSchool();
         result = 37 * result + this.getIdUser();
         return result;
   }   


}


