package co.com.carpco.altablero.hibernate.entities;
// Generated 30-oct-2014 21:20:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BzUser generated by hbm2java
 */
public class BzUser  implements java.io.Serializable {


     private Integer id;
     private String documentNumber;
     private String documentType;
     private String name;
     private String lastName;
     private Date born;
     private String address;
     private long phone1;
     private Long phone2;
     private String password;
     private String gender;
     private byte[] photo;
     private Date creation;
     private Date updated;
     private boolean enabled;
     private Set bzSchoolXusers = new HashSet(0);
     private Set bzClassRoomXusers = new HashSet(0);
     private Set bzClasses = new HashSet(0);
     private Set bzUserXuserTypes = new HashSet(0);

    public BzUser() {
    }

	
    public BzUser(String documentNumber, String documentType, String name, String lastName, Date born, String address, long phone1, String gender, Date creation, Date updated, boolean enabled) {
        this.documentNumber = documentNumber;
        this.documentType = documentType;
        this.name = name;
        this.lastName = lastName;
        this.born = born;
        this.address = address;
        this.phone1 = phone1;
        this.gender = gender;
        this.creation = creation;
        this.updated = updated;
        this.enabled = enabled;
    }
    public BzUser(String documentNumber, String documentType, String name, String lastName, Date born, String address, long phone1, Long phone2, String password, String gender, byte[] photo, Date creation, Date updated, boolean enabled, Set bzSchoolXusers, Set bzClassRoomXusers, Set bzClasses, Set bzUserXuserTypes) {
       this.documentNumber = documentNumber;
       this.documentType = documentType;
       this.name = name;
       this.lastName = lastName;
       this.born = born;
       this.address = address;
       this.phone1 = phone1;
       this.phone2 = phone2;
       this.password = password;
       this.gender = gender;
       this.photo = photo;
       this.creation = creation;
       this.updated = updated;
       this.enabled = enabled;
       this.bzSchoolXusers = bzSchoolXusers;
       this.bzClassRoomXusers = bzClassRoomXusers;
       this.bzClasses = bzClasses;
       this.bzUserXuserTypes = bzUserXuserTypes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDocumentNumber() {
        return this.documentNumber;
    }
    
    public void setDocumentNumber(String documentNumber) {
        this.documentNumber = documentNumber;
    }
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getBorn() {
        return this.born;
    }
    
    public void setBorn(Date born) {
        this.born = born;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public long getPhone1() {
        return this.phone1;
    }
    
    public void setPhone1(long phone1) {
        this.phone1 = phone1;
    }
    public Long getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(Long phone2) {
        this.phone2 = phone2;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public Set getBzSchoolXusers() {
        return this.bzSchoolXusers;
    }
    
    public void setBzSchoolXusers(Set bzSchoolXusers) {
        this.bzSchoolXusers = bzSchoolXusers;
    }
    public Set getBzClassRoomXusers() {
        return this.bzClassRoomXusers;
    }
    
    public void setBzClassRoomXusers(Set bzClassRoomXusers) {
        this.bzClassRoomXusers = bzClassRoomXusers;
    }
    public Set getBzClasses() {
        return this.bzClasses;
    }
    
    public void setBzClasses(Set bzClasses) {
        this.bzClasses = bzClasses;
    }
    public Set getBzUserXuserTypes() {
        return this.bzUserXuserTypes;
    }
    
    public void setBzUserXuserTypes(Set bzUserXuserTypes) {
        this.bzUserXuserTypes = bzUserXuserTypes;
    }




}


