package co.com.carpco.altablero.hibernate.entities;
// Generated 11-nov-2014 9:05:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BzUser generated by hbm2java
 */
public class BzUser  implements java.io.Serializable {


     private Integer id;
     private BzUser bzUserByIdGuardian2;
     private BzUser bzUserByIdGuardian1;
     private String documentNumber;
     private String documentType;
     private String name;
     private String lastName;
     private Date born;
     private String address;
     private long phone1;
     private Long phone2;
     private String password;
     private String gender;
     private byte[] photo;
     private Date creation;
     private Date updated;
     private boolean enabled;
     private Set<BzSchoolXuser> bzSchoolXusers = new HashSet<BzSchoolXuser>(0);
     private Set<BzClassRoomXuser> bzClassRoomXusers = new HashSet<BzClassRoomXuser>(0);
     private Set<BzClass> bzClasses = new HashSet<BzClass>(0);
     private Set<BzUser> bzUsersForIdGuardian2 = new HashSet<BzUser>(0);
     private Set<BzClassRoom> bzClassRooms = new HashSet<BzClassRoom>(0);
     private Set<BzUser> bzUsersForIdGuardian1 = new HashSet<BzUser>(0);
     private Set<BzUserXuserType> bzUserXuserTypes = new HashSet<BzUserXuserType>(0);

    public BzUser() {
    }

	
    public BzUser(String documentNumber, String documentType, String name, String lastName, Date born, String address, long phone1, String gender, Date creation, Date updated, boolean enabled) {
        this.documentNumber = documentNumber;
        this.documentType = documentType;
        this.name = name;
        this.lastName = lastName;
        this.born = born;
        this.address = address;
        this.phone1 = phone1;
        this.gender = gender;
        this.creation = creation;
        this.updated = updated;
        this.enabled = enabled;
    }
    public BzUser(BzUser bzUserByIdGuardian2, BzUser bzUserByIdGuardian1, String documentNumber, String documentType, String name, String lastName, Date born, String address, long phone1, Long phone2, String password, String gender, byte[] photo, Date creation, Date updated, boolean enabled, Set<BzSchoolXuser> bzSchoolXusers, Set<BzClassRoomXuser> bzClassRoomXusers, Set<BzClass> bzClasses, Set<BzUser> bzUsersForIdGuardian2, Set<BzClassRoom> bzClassRooms, Set<BzUser> bzUsersForIdGuardian1, Set<BzUserXuserType> bzUserXuserTypes) {
       this.bzUserByIdGuardian2 = bzUserByIdGuardian2;
       this.bzUserByIdGuardian1 = bzUserByIdGuardian1;
       this.documentNumber = documentNumber;
       this.documentType = documentType;
       this.name = name;
       this.lastName = lastName;
       this.born = born;
       this.address = address;
       this.phone1 = phone1;
       this.phone2 = phone2;
       this.password = password;
       this.gender = gender;
       this.photo = photo;
       this.creation = creation;
       this.updated = updated;
       this.enabled = enabled;
       this.bzSchoolXusers = bzSchoolXusers;
       this.bzClassRoomXusers = bzClassRoomXusers;
       this.bzClasses = bzClasses;
       this.bzUsersForIdGuardian2 = bzUsersForIdGuardian2;
       this.bzClassRooms = bzClassRooms;
       this.bzUsersForIdGuardian1 = bzUsersForIdGuardian1;
       this.bzUserXuserTypes = bzUserXuserTypes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public BzUser getBzUserByIdGuardian2() {
        return this.bzUserByIdGuardian2;
    }
    
    public void setBzUserByIdGuardian2(BzUser bzUserByIdGuardian2) {
        this.bzUserByIdGuardian2 = bzUserByIdGuardian2;
    }
    public BzUser getBzUserByIdGuardian1() {
        return this.bzUserByIdGuardian1;
    }
    
    public void setBzUserByIdGuardian1(BzUser bzUserByIdGuardian1) {
        this.bzUserByIdGuardian1 = bzUserByIdGuardian1;
    }
    public String getDocumentNumber() {
        return this.documentNumber;
    }
    
    public void setDocumentNumber(String documentNumber) {
        this.documentNumber = documentNumber;
    }
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getBorn() {
        return this.born;
    }
    
    public void setBorn(Date born) {
        this.born = born;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public long getPhone1() {
        return this.phone1;
    }
    
    public void setPhone1(long phone1) {
        this.phone1 = phone1;
    }
    public Long getPhone2() {
        return this.phone2;
    }
    
    public void setPhone2(Long phone2) {
        this.phone2 = phone2;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public Set<BzSchoolXuser> getBzSchoolXusers() {
        return this.bzSchoolXusers;
    }
    
    public void setBzSchoolXusers(Set<BzSchoolXuser> bzSchoolXusers) {
        this.bzSchoolXusers = bzSchoolXusers;
    }
    public Set<BzClassRoomXuser> getBzClassRoomXusers() {
        return this.bzClassRoomXusers;
    }
    
    public void setBzClassRoomXusers(Set<BzClassRoomXuser> bzClassRoomXusers) {
        this.bzClassRoomXusers = bzClassRoomXusers;
    }
    public Set<BzClass> getBzClasses() {
        return this.bzClasses;
    }
    
    public void setBzClasses(Set<BzClass> bzClasses) {
        this.bzClasses = bzClasses;
    }
    public Set<BzUser> getBzUsersForIdGuardian2() {
        return this.bzUsersForIdGuardian2;
    }
    
    public void setBzUsersForIdGuardian2(Set<BzUser> bzUsersForIdGuardian2) {
        this.bzUsersForIdGuardian2 = bzUsersForIdGuardian2;
    }
    public Set<BzClassRoom> getBzClassRooms() {
        return this.bzClassRooms;
    }
    
    public void setBzClassRooms(Set<BzClassRoom> bzClassRooms) {
        this.bzClassRooms = bzClassRooms;
    }
    public Set<BzUser> getBzUsersForIdGuardian1() {
        return this.bzUsersForIdGuardian1;
    }
    
    public void setBzUsersForIdGuardian1(Set<BzUser> bzUsersForIdGuardian1) {
        this.bzUsersForIdGuardian1 = bzUsersForIdGuardian1;
    }
    public Set<BzUserXuserType> getBzUserXuserTypes() {
        return this.bzUserXuserTypes;
    }
    
    public void setBzUserXuserTypes(Set<BzUserXuserType> bzUserXuserTypes) {
        this.bzUserXuserTypes = bzUserXuserTypes;
    }




}


