package co.com.carpco.altablero.hibernate.entities;
// Generated 30-oct-2014 21:20:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BzYear generated by hbm2java
 */
public class BzYear  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Date creation;
     private Date updated;
     private boolean enabled;
     private Set bzClassRooms = new HashSet(0);
     private Set bzPeriods = new HashSet(0);

    public BzYear() {
    }

	
    public BzYear(String name, Date creation, Date updated, boolean enabled) {
        this.name = name;
        this.creation = creation;
        this.updated = updated;
        this.enabled = enabled;
    }
    public BzYear(String name, Date creation, Date updated, boolean enabled, Set bzClassRooms, Set bzPeriods) {
       this.name = name;
       this.creation = creation;
       this.updated = updated;
       this.enabled = enabled;
       this.bzClassRooms = bzClassRooms;
       this.bzPeriods = bzPeriods;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public Set getBzClassRooms() {
        return this.bzClassRooms;
    }
    
    public void setBzClassRooms(Set bzClassRooms) {
        this.bzClassRooms = bzClassRooms;
    }
    public Set getBzPeriods() {
        return this.bzPeriods;
    }
    
    public void setBzPeriods(Set bzPeriods) {
        this.bzPeriods = bzPeriods;
    }




}


