package co.com.carpco.altablero.hibernate.entities;
// Generated 30-oct-2014 21:20:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CnAccess generated by hbm2java
 */
public class CnAccess  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String name;
     private Date creation;
     private Date updated;
     private boolean enabled;
     private Set cnUsertTypeXaccesses = new HashSet(0);

    public CnAccess() {
    }

	
    public CnAccess(String code, String name, Date creation, Date updated, boolean enabled) {
        this.code = code;
        this.name = name;
        this.creation = creation;
        this.updated = updated;
        this.enabled = enabled;
    }
    public CnAccess(String code, String name, Date creation, Date updated, boolean enabled, Set cnUsertTypeXaccesses) {
       this.code = code;
       this.name = name;
       this.creation = creation;
       this.updated = updated;
       this.enabled = enabled;
       this.cnUsertTypeXaccesses = cnUsertTypeXaccesses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public Set getCnUsertTypeXaccesses() {
        return this.cnUsertTypeXaccesses;
    }
    
    public void setCnUsertTypeXaccesses(Set cnUsertTypeXaccesses) {
        this.cnUsertTypeXaccesses = cnUsertTypeXaccesses;
    }




}


