package co.com.carpco.altablero.hibernate.entities;
// Generated 11-nov-2014 9:05:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CnUserType generated by hbm2java
 */
public class CnUserType  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String name;
     private Date creation;
     private Date updated;
     private boolean enabled;
     private Set<CnUsertTypeXaccess> cnUsertTypeXaccesses = new HashSet<CnUsertTypeXaccess>(0);
     private Set<BzUserXuserType> bzUserXuserTypes = new HashSet<BzUserXuserType>(0);

    public CnUserType() {
    }

	
    public CnUserType(String code, String name, Date creation, Date updated, boolean enabled) {
        this.code = code;
        this.name = name;
        this.creation = creation;
        this.updated = updated;
        this.enabled = enabled;
    }
    public CnUserType(String code, String name, Date creation, Date updated, boolean enabled, Set<CnUsertTypeXaccess> cnUsertTypeXaccesses, Set<BzUserXuserType> bzUserXuserTypes) {
       this.code = code;
       this.name = name;
       this.creation = creation;
       this.updated = updated;
       this.enabled = enabled;
       this.cnUsertTypeXaccesses = cnUsertTypeXaccesses;
       this.bzUserXuserTypes = bzUserXuserTypes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    public Set<CnUsertTypeXaccess> getCnUsertTypeXaccesses() {
        return this.cnUsertTypeXaccesses;
    }
    
    public void setCnUsertTypeXaccesses(Set<CnUsertTypeXaccess> cnUsertTypeXaccesses) {
        this.cnUsertTypeXaccesses = cnUsertTypeXaccesses;
    }
    public Set<BzUserXuserType> getBzUserXuserTypes() {
        return this.bzUserXuserTypes;
    }
    
    public void setBzUserXuserTypes(Set<BzUserXuserType> bzUserXuserTypes) {
        this.bzUserXuserTypes = bzUserXuserTypes;
    }




}


