package co.com.carpco.altablero.hibernate.entities;
// Generated 11-nov-2014 9:05:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CnUsertTypeXaccess generated by hbm2java
 */
public class CnUsertTypeXaccess  implements java.io.Serializable {


     private CnUsertTypeXaccessId id;
     private CnAccess cnAccess;
     private CnUserType cnUserType;
     private Date creation;
     private Date updated;
     private boolean enabled;

    public CnUsertTypeXaccess() {
    }

    public CnUsertTypeXaccess(CnUsertTypeXaccessId id, CnAccess cnAccess, CnUserType cnUserType, Date creation, Date updated, boolean enabled) {
       this.id = id;
       this.cnAccess = cnAccess;
       this.cnUserType = cnUserType;
       this.creation = creation;
       this.updated = updated;
       this.enabled = enabled;
    }
   
    public CnUsertTypeXaccessId getId() {
        return this.id;
    }
    
    public void setId(CnUsertTypeXaccessId id) {
        this.id = id;
    }
    public CnAccess getCnAccess() {
        return this.cnAccess;
    }
    
    public void setCnAccess(CnAccess cnAccess) {
        this.cnAccess = cnAccess;
    }
    public CnUserType getCnUserType() {
        return this.cnUserType;
    }
    
    public void setCnUserType(CnUserType cnUserType) {
        this.cnUserType = cnUserType;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }




}


